youtube = "https://awa.com"
github = "https://awa.com"
title = "Rafael Dev"
description = "Este site é bom demais!"
featured_image = "/images/hero.jpg"
theme = "ananke"
recent_posts_number = 2
facebook = "https://awa.com"
twitter = "https://awa.com"
instagram = "https://awa.com"
gitlab = "https://awa.com"
stackoverflow = "https://awa.com"
baseURL = "https://priceless-edison-f72052.netlify.app/"
linkedin = "https://awa.com"
SectionPagesMenu = "main"

[params]
background_color_class_secondary = "bg-white"
description = "Este site é bom demais!"
featured_image = "./images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2
twitter = ""
instagram = "https://www.instagram.com/https_rafael/"
youtube = ""
site_logo = ""
facebook = "https://www.facebook.com/rafael.mesquita.7927/"
github = "https://github.com/rafaelmesquita-ceara"
mastodon = ""
stackoverflow = ""
background_color_class = "bg-black"
slack = ""
rss = ""
favicon = ""
gitlab = ""
linkedin = "www.linedin.com/in/rafael-mesquita-a59a631a6"