title = "Blog do Rafa"
baseURL = "https://priceless-edison-f72052.netlify.app/"
theme = "ananke"
SectionPagesMenu = "main"

[params]
background_color_class_secondary = "bg-white"
youtube = ""
site_logo = ""
github = "https://github.com/rafaelmesquita-ceara"
facebook = "https://www.facebook.com/rafael.mesquita.7927/"
mastodon = ""
featured_image = "/images/hero.jpg"
stackoverflow = ""
background_color_class = "bg-black"
slack = ""
rss = ""
instagram = "https://www.instagram.com/https_rafael/"
twitter = ""
favicon = ""
recent_posts_number = 2
gitlab = ""
description = "Este site é bom demais!"
linkedin = "www.linedin.com/in/rafael-mesquita-a59a631a6"