title = "Rafael Dev"
baseURL = "https://priceless-edison-f72052.netlify.app/"
theme = "ananke"
SectionPagesMenu = "main"

[params]
favicon = ""
site_logo = ""
description = "Este site é bom demais!"
facebook = "https://www.facebook.com/rafael.mesquita.7927/"
twitter = ""
instagram = "https://www.instagram.com/https_rafael/"
youtube = ""
github = "https://github.com/rafaelmesquita-ceara"
gitlab = ""
linkedin = "www.linedin.com/in/rafael-mesquita-a59a631a6"
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
background_color_class_secondary = "bg-white"
featured_image = "./images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2